### ISSUE TITLE
Always need OP to set skin

### ISSUE THREAD

**Issue by nosekefik** [sekwah41/Re-Skin#104]
I have the option setSelfSkinsNeedsOp = false but when a non OP player uses /setskin it not works, and appears a message that he need OP.
I'm using the latest version on CurseForge (2.5.1) on minecraft 1.18.2 Forge

**Comment by sekwah41** [comment]
Are you sure you are on 2.5.1? Im pretty sure we added a fix for that last update.

What is the exact command you are typing?

**Comment by nosekefik** [comment]
Yes I'm on 2.5.1
I tried with /setskin https://i.imgur.com/mORJxcm.png
![image](https://user-images.githubusercontent.com/562618/191137893-c50ddc0b-9d42-46dd-aa9f-3a3326fb02f9.png)
![image](https://user-images.githubusercontent.com/562618/191138779-047ed099-d07e-4945-99c4-b07763393649.png)

**Comment by sekwah41** [comment]
I'll try to re-create it tomorrow

**Comment by sekwah41** [comment]
Just looking back through issues. I think I couldn't recreate it but I'll need to check.

**Comment by sekwah41** [comment]
I will keep an eye on this, I just have been trying to set someone else's skin or something though I have fixed one permission issue I am unsure if this was it.

I know its been a while since the report but could you check if you are still having the issue on the latest version?  If you are still having the issue would you be able to send your server.properties and re-skin config?
