### ISSUE TITLE
Resource pack support

### ISSUE THREAD

**Issue by StrideyGH** [sekwah41/Re-Skin#92]
I'd love if you could assign skins to users via their username or UUID in a resource pack! 
My idea is that you would have a folder in resource packs, something like 'assets/reskin/textures/players/' and the textures' file names would be a username or UUID, which would retexture that player.

**Comment by sekwah41** [comment]
Sorry for the inactivity on this. I think I can see what you are suggesting but not too sure I see it getting used much. Im going to try to focus on other features such as the server sending the image data rather than needing each client to download it.

I can re-open the issue if there is a solid usecase though :)
